### ISSUE TITLE
"b" error

### ISSUE THREAD

**Issue by JohnMcKay** [tiepvupsu/DFDL#1]
Sometimes when I build a dictionary I get a repeated "b" and then the DFDL algorithm wonks out.  What's going on?

Seems like it's an error with the update function - some dimension conflict?

**Comment by tiepvupsu** [comment]
Thank you for pointing out this bug. I actually fixed this in the last version. 

The bug happened since I shrinked dictionaries if there are some unused atoms in those. In the new version, I keep those atoms there, so you wouldn't see that bug.
Bests,
